export interface AppTheme {
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  bgColor: string;
  textColor: string;
  cardBg: string;
  borderRadius: 'rounded-none' | 'rounded-lg' | 'rounded-2xl' | 'rounded-3xl' | 'rounded-full';
  fontFamily: string;
  isDark: boolean;
  buttonGradient?: string;
}

export interface AppTab {
  id: string;
  label: string;
  icon: string;
}

export interface AppCategory {
  id: string;
  label: string;
  icon: string;
  count?: string;
}

export interface AppItem {
  id: string;
  title: string;
  subtitle: string;
  price?: string;
  rating?: number;
  tag?: string;
  imageEmoji: string;
  category?: string;
  details?: string;
  isLiked?: boolean;
  completed?: boolean;
}

export interface AppBanner {
  title: string;
  subtitle: string;
  buttonText: string;
  gradient: string;
}

export interface InteractiveWidget {
  id: string;
  type: 'chat_stream' | 'task_list' | 'counter_stat' | 'form_input' | 'card_grid';
  title?: string;
  data: any;
}

export interface AppScreen {
  title: string;
  headerSubtitle?: string;
  banner?: AppBanner;
  searchPlaceholder?: string;
  categories?: AppCategory[];
  items: AppItem[];
  widgets?: InteractiveWidget[];
  actionButton?: {
    text: string;
    color?: string;
    actionType?: string;
  };
}

export interface CustomButtonConfig {
  id: string;
  text: string;
  bgColor: string;
  textColor: string;
  shape: 'rounded-md' | 'rounded-xl' | 'rounded-2xl' | 'rounded-full';
  icon: string;
  action: string;
  gradient?: string;
  glow?: boolean;
}

export interface MobileAppConfig {
  id: string;
  name: string;
  category: string;
  isBuilt: boolean; // Indicates if an app has been generated by user prompt
  theme: AppTheme;
  navigation: {
    title: string;
    showBack: boolean;
    tabs: AppTab[];
    activeTab: string;
  };
  screens: Record<string, AppScreen>;
  customButton: CustomButtonConfig;
  hasCustomButton?: boolean;
  showSearch?: boolean;
  showBanner?: boolean;
  cartCount: number;
  walletBalance?: string;
  userName?: string;
  lastUpdatedField?: string;
  chatMessagesDemo?: Array<{ id: string; sender: 'me' | 'other'; text: string; time: string }>;
}

export interface ZipFileInfo {
  name: string;
  size: number;
  date: Date;
  isDir: boolean;
  contentSnippet?: string;
}

export interface SmartZipCore {
  fileName: string;
  fileCount: number;
  files: ZipFileInfo[];
  manifest: {
    name: string;
    version: string;
    engine: string;
    libraries: string[];
    capabilities: string[];
    componentsCount: number;
  };
  isLoaded: boolean;
  loadedAt: Date | null;
  rawZipBlob?: Blob;
  embeddedAppConfig?: Partial<MobileAppConfig>;
  customLibraries?: Record<string, string>;
}

export interface ChatMessage {
  id: string;
  sender: 'user' | 'assistant' | 'system';
  text: string;
  timestamp: Date;
  actionType?: string;
  diffInfo?: string;
  isAudio?: boolean;
}
